import requests
from bs4 import BeautifulSoup
import pandas as pd
from docx import Document
from docx.shared import Pt, RGBColor
from datetime import datetime

print("🚀 爆款挖掘机启动...")

# 1. 定义评分翻译字典 (把英文变成数字)
rating_map = {
    "One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5
}

# 存储找到的“黄金书”
golden_books = []

# 2. 扫描前 10 页 (模拟全站扫描)
for page in range(1, 11):
    url = f"http://books.toscrape.com/catalogue/page-{page}.html"
    print(f"📡 正在扫描第 {page} 页...")
    
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    books = soup.find_all("article", class_="product_pod")
    
    for book in books:
        # --- A. 获取评分 ---
        # 评分藏在 class 属性里，例如: class="star-rating Five"
        # 我们取第 2 个词 'Five'
        star_class = book.find("p", class_="star-rating")["class"][1]
        rating = rating_map.get(star_class, 0) # 查字典变成数字
        
        # --- B. 获取价格 ---
        price_text = book.find("p", class_="price_color").text
        # 去掉 '£' 并转为小数
        price = float(price_text.replace("£", "").replace("Â", ""))
        
        # --- C. 核心筛选逻辑 (商业价值所在) ---
        # 客户要求：5星 且 价格小于 20
        if rating == 5 and price < 20:
            title = book.h3.a["title"]
            print(f"   💰 发现爆款: {title} (£{price})")
            
            golden_books.append({
                "书名": title,
                "价格": price,
                "评分": "⭐⭐⭐⭐⭐"
            })

print("-" * 30)
print(f"🎉 扫描结束！共找到 {len(golden_books)} 本黄金书籍。")

# 3. 生成 Word 采购报告 (交付物)
print("📝 正在生成采购清单...")

doc = Document()
doc.add_heading('Best Value Books Report', 0)
doc.add_paragraph(f"Generated by: Yang's Bot | Date: {datetime.now().strftime('%Y-%m-%d')}")
doc.add_paragraph(f"Criteria: 5-Star Rating & Price < £20")

# --- 在 Word 里画表格 ---
# 创建一个表：行数=书籍数量+1(表头)，列数=3
table = doc.add_table(rows=1, cols=3)
table.style = 'Table Grid' # 给表格加边框

# 设置表头
hdr_cells = table.rows[0].cells
hdr_cells[0].text = 'Book Title'
hdr_cells[1].text = 'Price (£)'
hdr_cells[2].text = 'Rating'

# 填入数据
for item in golden_books:
    row_cells = table.add_row().cells
    row_cells[0].text = item['书名']
    row_cells[1].text = str(item['价格'])
    row_cells[2].text = item['评分']

# 保存
filename = "Golden_Books_Purchase_List.docx"
doc.save(filename)

print(f"✅ 交付文件已就绪: [{filename}]")
print("这单 $60 赚到手了！快去打开看看！")